import AppLayout from '@/components/layout/AppLayout';
import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import 'react-toastify/dist/ReactToastify.css';
import '../styles/globals.css';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider count={30}>
      <html lang="en">
        <body className={inter.className}>
          <AppLayout>{children}</AppLayout>
        </body>
      </html>
    </StoreProvider>
  );
}
