import React from 'react';
import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import 'react-toastify/dist/ReactToastify.css';
import AppLayout from '@/components/layout/AppLayout';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>{children}</body>
    // </html>
    <StoreProvider count={30}>
      <html lang="en">
        {/* <Head>
          <meta name="viewport" content={'width=device-width, initial-scale=1'} />
        </Head> */}

        <body className={inter.className}>
          <AppLayout>{children}</AppLayout>
        </body>
      </html>
    </StoreProvider>
  );
}
