export default {
  SITE_DOMAIN: process.env.NEXT_PUBLIC_SITE_DOMAIN_URL,
  THEME_DEFAULT: 'dark',
  THEME_DARK: 'dark',
  THEME_LIGHT: 'light',
  LANGUAGE_BROWSER_DEFAULT: 'us-US',
  MY_USERNAME_CREDITS_CREATOR: 'grigoar',
  CREDITS_CREATOR_ANONYM: 'Anonymous',
  LOCAL_STORAGE_TM_OBJECT_FLAGS: 'TM_flags',
  SUPPORT_EMAIL: 'contact@typingmuscle.com',
  SITE_NAME: 'JobsInTech',
  TYPING_MUSCLE_LOGO: 'https://typing-muscle.s3.eu-central-1.amazonaws.com/TM-images/TypingMuscle-Logo-small.png',
  LOCAL_STORAGE_THEME: 'theme',

  // Cookies names (for cookie consent)
  COOKIE_AUTH_NAME: 'jwt',
  COOKIE_AUTH_NAME_EXPIRED: 'loggedout',
  COOKIE_CONSENT: 'cookie_consent',
  COOKIE_CONSENT_COUNTRY: 'ccc',
  USER_PREMIUM_COOKIE: 'up',
  GOOGLE_ADSENSE_SCRIPT_ID: 'google-adsense-script',
  GOOGLE_TAG_ID: 'G-XGMJKV933Z',

  // Default Values
  PRACTICE_DEFAULT_TEXT: `Try out this fancy custom text! \nLet's have fun! #mytext`,
  TYPING_HIDE_WPM_START_RACE_TIMER_MS: 500, // ms
  USER_SETTINGS_DEBOUNCE_SAVE_TIMER_MS: 1500, // ms
  ACCURACY_REAL_MODE_DEFAULT: false,
  RACE_RESULTS_AUTO_SCROLL_DEFAULT: true,
  SHOW_CHARACTERS_STATS_ON_RACE_RESULTS_DEFAULT: true,
  SHOW_FINGERS_STATS_ON_RACE_RESULTS_DEFAULT: true,
  IS_SELECT_PRACTICE_TEXT_OPEN_DEFAULT: true,
  SHOW_KEYBOARD_CHARACTERS_ACCURACY_DEFAULT: true,
  SHOW_KEYBOARD_FINGERS_ACCURACY_DEFAULT: true,
  SHOW_WPM_FLAG_DEFAULT: true,
  SHOW_TYPING_TIPS_DEFAULT: false,
  SHOW_WRONG_KEY_TOOLTIP: true,
  SHOW_WRONG_KEY_TOOLTIP_MS: 500,
  TEXT_SIZE_FLAG_DEFAULT: 'M',
  INACTIVE_COUNTDOWN_TIMER_VALUE: -1,
  COUNTDOWN_TIMER_BUTTON_DISABLED: 15,
  MIN_ACCURACY_TO_FINISH_RACE: 80,
  DELAY_API_CALLS_TIME_MS: 1000,
  TEXT_PRACTICE_MAX_LENGTH: 5000,
  // ENTER_KEY_STRING: 'ᘕ',
  ENTER_KEY_STRING: '‽',
  PADDING_PRACTICE_TEXT_NORMAL: '10px',
  PADDING_PRACTICE_TEXT_BEGINNERS: '25px 10px 10px 15px',
  CHANGE_EMAIL_TEXT_CONFIRM: 'change email',

  // Tags
  USER_PROFILE_TAG: 'USER_PROFILE',
  // RANDOM_RACE_ID_TAG: 'RANDOM',
  // USER_RACES_TAG: 'USER_RACES_TAG',
  // RACE_DATA_TAG: 'RACE_DATA_TAG',
  // USER_GENERAL_STATS_TAG: 'USER_GENERAL_STATS',
  // USER_IMPROVE_STATS_TAG: 'USER_IMPROVE_STATS',
  // USER_PRACTICE_DATA_TAG: 'USER_PRACTICE_DATA',
  // USER_FEEDBACK_TAG: 'USER_FEEDBACK_TAG',
  // USER_PROPOSAL_TEXT_TAG: 'USER_PROPOSAL_TEXT_TAG',
  USER_SETTING_TAG: 'USER_SETTING_TAG',
  PAYMENT_TAG: 'PAYMENT_TAG',
  // USER_PROFILE_DETAILS_BY_ID_TAG: 'USER_PROFILE_DETAILS_BY_ID',
  GUEST_USER_TAG: 'GUEST_USER',
  JOB_POSTS_TAG: 'JOB_POST',
  COMPANIES_TAG: 'COMPANIES',

  // Books Categories
  RANDOM_RACE_TYPE: 'RANDOM',
  BOOKS_RACE_CATEGORY: 'BOOKS',
  JOKES_RACE_CATEGORY: 'JOKES',
  QUOTES_RACE_CATEGORY: 'QUOTES',
  BEGINNER_RACE_CATEGORY: 'BEGINNER',
  SPEED_IMPROVEMENT_RACE_CATEGORY: 'SPEED_IMPROVEMENT',
  ALL_RACE_CATEGORIES: 'ALL_RACES_TYPE',
  EN_1K_CATEGORY: 'EN_1K',
  EN_5K_CATEGORY: 'EN_5K',
  EN_10K_CATEGORY: 'EN_10K',
  DEFAULT_ELEMENTS_LIST_LANG: 50,
  EN_1K_RACE_ID: 'RANDOM_EN_1K',
  EN_5K_RACE_ID: 'RANDOM_EN_5K',
  EN_10K_RACE_ID: 'RANDOM_EN_10K',
  RANDOM_ELEMENTS_NR_LOW: 15,
  RANDOM_ELEMENTS_NR_MED: 30,
  RANDOM_ELEMENTS_NR_HIGH: 45,
  BEGINNER_POINTS: 30,
  SPEED_IMPROVEMENT_POINTS: 70,
  BEGINNER_RACE_DEFAULT_MIN_WPM: 30,
  ONE_STAR_ACCURACY_MIN: 50,
  TWO_STAR_ACCURACY_MIN: 90,
  THREE_STAR_ACCURACY_MIN: 90,

  // Crypto Addresses Reducer Types
  BTC_COPY_ADDRESS: 'BTC_COPY_ADDRESS',
  BTC_CHANGE_FOCUS_QR: 'BTC_CHANGE_FOCUS_QR',
  ETH_COPY_ADDRESS: 'ETH_COPY_ADDRESS',
  ETH_CHANGE_FOCUS_QR: 'ETH_CHANGE_FOCUS_QR',
  XLM_COPY_ADDRESS: 'XLM_COPY_ADDRESS',
  XLM_COPY_MEMO: 'XLM_COPY_MEMO',
  XLM_CHANGE_FOCUS_QR: 'XLM_CHANGE_FOCUS_QR',
  DOGE_COPY_ADDRESS: 'DOGE_COPY_ADDRESS',
  DOGE_CHANGE_FOCUS_QR: 'DOGE_CHANGE_FOCUS_QR',

  // Practice Texts
  PRACTICE_TEXT_1: 'TM_PRACTICE_TEXT_1',
  PRACTICE_TEXT_2: 'TM_PRACTICE_TEXT_2',
  PRACTICE_TEXT_3: 'TM_PRACTICE_TEXT_3',
  PRACTICE_TEXT_ACTIVE_NR_EMPTY: 'TM_practice_text_active_empty',

  // Letters Check
  LETTER_NORMAL_STATE: 'normal',
  LETTER_CORRECT_STATE: 'correct',
  LETTER_INCORRECT_STATE: 'incorrect',
  LETTER_RECTIFIED_STATE: 'rectified',

  // Elements
  LOADING_SPINNER_HEIGHT_MAX_ELEMENT: 'element',
  LOADING_SPINNER_HEIGHT_MAX_SCREEN: 'full',

  // Links default
  IMAGE_JOKES_DEFAULT: 'staticImages/funny-default.jpg',
  TITLE_JOKES: 'Dad Jokes - Over 600 Jokes',
  LINK_JOKES_AMAZON: 'https://www.amazon.com/Dad-Jokes-Good-Clean-Ages/dp/1492675377',

  IMAGE_QUOTES_DEFAULT: 'staticImages/quotes-default.jpg',
  TITLE_QUOTES: 'Mindset - Recommended book (QUOTES)',
  LINK_QUOTES_AMAZON: 'https://www.amazon.com/Mindset-Psychology-Carol-S-Dweck/dp/0345472322',

  IMAGE_RANDOM_DEFAULT: 'staticImages/random-words-default.jpg',
  TITLE_RANDOM: 'Mindset - Recommended book (RANDOM)',
  LINK_RANDOM_AMAZON: 'https://www.amazon.com/Mindset-Psychology-Carol-S-Dweck/dp/0345472322',

  IMAGE_BEGINNER_DEFAULT: 'staticImages/beginner-default.jpg',
  IMAGE_SPEED_IMPROVEMENT_DEFAULT: 'staticImages/speed-rocket-default.jpg',

  // Backend email confirmation expiration hours (48h for now)
  EMAIL_CONFIRMATION_EXPIRES_IN_HOURS: 48 * 60 * 60 * 1000,

  // USER ROLES
  USER_ROLE_ADMIN: 'ADMIN',
  USER_ROLE_USER: 'USER',
  USER_ROLE_POWER_USER: 'POWER_USER',

  // USER FEEDBACK/PROPOSALS STATUSES
  NEW_TICKET_STATUS: 'NEW',
  PENDING_TICKET_STATUS: 'PENDING',
  RESOLVED_TICKET_STATUS: 'RESOLVED',
  ALL_TICKETS_STATUSES: 'ALL_TICKETS_STATUSES',

  DEFAULT_RACE_POINTS: 70,
  EN_1K_POINTS: 70,
  EN_5K_POINTS: 90,
  EN_10K_POINTS: 110,

  // CURRENCIES LIST
  // Donation amounts
  CURRENCIES_LIST: ['AUD', 'CAD', 'EUR', 'RON', 'USD', 'GBP'],
  DEFAULT_CURRENCY: 'usd',
  SMALL_DONATION_AMOUNT: 'SMALL_DONATION_AMOUNT',
  MEDIUM_DONATION_AMOUNT: 'MEDIUM_DONATION_AMOUNT',
  BIG_DONATION_AMOUNT: 'BIG_DONATION_AMOUNT',
  CUSTOM_DONATION_AMOUNT: 'CUSTOM_DONATION_AMOUNT',

  SMALL_DONATION_AMOUNT_VALUE_USD: 7.99,
  MEDIUM_DONATION_AMOUNT_VALUE_USD: 9.99,
  BIG_DONATION_AMOUNT_VALUE_USD: 19.99,
  CUSTOM_DONATION_AMOUNT_VALUE_USD: 73.57,
  MIN_DONATION_AMOUNT_VALUE_USD: 1,
  MAX_DONATION_AMOUNT_VALUE_USD: 1000,

  SMALL_DONATION_AMOUNT_VALUE_EUR: 7.99,
  MEDIUM_DONATION_AMOUNT_VALUE_EUR: 9.99,
  BIG_DONATION_AMOUNT_VALUE_EUR: 19.99,
  CUSTOM_DONATION_AMOUNT_VALUE_EUR: 73.57,
  MIN_DONATION_AMOUNT_VALUE_EUR: 1,
  MAX_DONATION_AMOUNT_VALUE_EUR: 1000,

  SMALL_DONATION_AMOUNT_VALUE_GBP: 6.99,
  MEDIUM_DONATION_AMOUNT_VALUE_GBP: 9.99,
  BIG_DONATION_AMOUNT_VALUE_GBP: 19.99,
  CUSTOM_DONATION_AMOUNT_VALUE_GBP: 73.57,
  MIN_DONATION_AMOUNT_VALUE_GBP: 1,
  MAX_DONATION_AMOUNT_VALUE_GBP: 1000,

  SMALL_DONATION_AMOUNT_VALUE_RON: 29.99,
  MEDIUM_DONATION_AMOUNT_VALUE_RON: 49.99,
  BIG_DONATION_AMOUNT_VALUE_RON: 99.99,
  CUSTOM_DONATION_AMOUNT_VALUE_RON: 143.57,
  MIN_DONATION_AMOUNT_VALUE_RON: 5,
  MAX_DONATION_AMOUNT_VALUE_RON: 5000,

  SMALL_DONATION_AMOUNT_VALUE_AUD: 9.99,
  MEDIUM_DONATION_AMOUNT_VALUE_AUD: 9.99,
  BIG_DONATION_AMOUNT_VALUE_AUD: 19.99,
  CUSTOM_DONATION_AMOUNT_VALUE_AUD: 73.57,
  MIN_DONATION_AMOUNT_VALUE_AUD: 1,
  MAX_DONATION_AMOUNT_VALUE_AUD: 1000,

  SMALL_DONATION_AMOUNT_VALUE_CAD: 9.99,
  MEDIUM_DONATION_AMOUNT_VALUE_CAD: 9.99,
  BIG_DONATION_AMOUNT_VALUE_CAD: 19.99,
  CUSTOM_DONATION_AMOUNT_VALUE_CAD: 73.57,
  MIN_DONATION_AMOUNT_VALUE_CAD: 1,
  MAX_DONATION_AMOUNT_VALUE_CAD: 1000,

  WEBSITE_SEO_KEYWORDS_DEFAULT:
    'touch typing, learn touch typing, typing game, typing test, speed test, speed typing test, free typing website, typing for kids, beginner typing, learn typing',

  // GDPR countries
  countriesGDPR: [
    'AT',
    'BE',
    'BG',
    'HR',
    'CY',
    'CZ',
    'DK',
    'EE',
    'FI',
    'FR',
    'DE',
    'GR',
    'HU',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MT',
    'NL',
    'PL',
    'PT',
    'RO',
    'SK',
    'SI',
    'ES',
    'SE',
    'GB',
    'CA',
    // 'AU', // Australia's Privacy Act may require user consent for online advertising.
    'BR', // Brazil has the Lei Geral de Proteção de Dados (LGPD), which imposes consent requirements for data processing, including advertising.
    // 'KR', // South Korea: South Korea's Personal Information Protection Act (PIPA) regulates data processing and may require user consent for advertising.
    // 'JP', // Japan has the Act on the Protection of Personal Information (APPI), which may require consent for online advertising.
    // 'SG', // Singapore's Personal Data Protection Act (PDPA) may require user consent for online advertising.

    // 'AR', // Argentina has data protection regulations under the Personal Data Protection Law, which may require consent for advertising.
    // "California"
    // "IN",// India's Personal Data Protection Bill, once enacted, may require consent for online advertising.
  ],

  // https://stackoverflow.com/questions/2388115/get-locale-short-date-format-using-javascript
  DATE_TIMEZONE_FORMAT_OBJ: {
    'af-ZA': 'yyyy/MM/dd',
    'am-ET': 'd/M/yyyy',
    'ar-AE': 'dd/MM/yyyy',
    'ar-BH': 'dd/MM/yyyy',
    'ar-DZ': 'dd-MM-yyyy',
    'ar-EG': 'dd/MM/yyyy',
    'ar-IQ': 'dd/MM/yyyy',
    'ar-JO': 'dd/MM/yyyy',
    'ar-KW': 'dd/MM/yyyy',
    'ar-LB': 'dd/MM/yyyy',
    'ar-LY': 'dd/MM/yyyy',
    'ar-MA': 'dd-MM-yyyy',
    'ar-OM': 'dd/MM/yyyy',
    'ar-QA': 'dd/MM/yyyy',
    'ar-SA': 'dd/MM/yy',
    'ar-SY': 'dd/MM/yyyy',
    'ar-TN': 'dd-MM-yyyy',
    'ar-YE': 'dd/MM/yyyy',
    'arn-CL': 'dd-MM-yyyy',
    'as-IN': 'dd-MM-yyyy',
    'az-Cyrl-AZ': 'dd.MM.yyyy',
    'az-Latn-AZ': 'dd.MM.yyyy',
    'ba-RU': 'dd.MM.yy',
    'be-BY': 'dd.MM.yyyy',
    'bg-BG': 'dd.M.yyyy',
    'bn-BD': 'dd-MM-yy',
    'bn-IN': 'dd-MM-yy',
    'bo-CN': 'yyyy/M/d',
    'br-FR': 'dd/MM/yyyy',
    'bs-Cyrl-BA': 'd.M.yyyy',
    'bs-Latn-BA': 'd.M.yyyy',
    'ca-ES': 'dd/MM/yyyy',
    'co-FR': 'dd/MM/yyyy',
    'cs-CZ': 'd.M.yyyy',
    'cy-GB': 'dd/MM/yyyy',
    'da-DK': 'dd-MM-yyyy',
    'de-AT': 'dd.MM.yyyy',
    'de-CH': 'dd.MM.yyyy',
    'de-DE': 'dd.MM.yyyy',
    'de-LI': 'dd.MM.yyyy',
    'de-LU': 'dd.MM.yyyy',
    'dsb-DE': 'd. M. yyyy',
    'dv-MV': 'dd/MM/yy',
    'el-GR': 'd/M/yyyy',
    'en-029': 'MM/dd/yyyy',
    'en-AU': 'd/MM/yyyy',
    'en-BZ': 'dd/MM/yyyy',
    'en-CA': 'dd/MM/yyyy',
    'en-GB': 'dd/MM/yyyy',
    'en-IE': 'dd/MM/yyyy',
    'en-IN': 'dd-MM-yyyy',
    'en-JM': 'dd/MM/yyyy',
    'en-MY': 'd/M/yyyy',
    'en-NZ': 'd/MM/yyyy',
    'en-PH': 'M/d/yyyy',
    'en-SG': 'd/M/yyyy',
    'en-TT': 'dd/MM/yyyy',
    'en-US': 'M/d/yyyy',
    'en-ZA': 'yyyy/MM/dd',
    'en-ZW': 'M/d/yyyy',
    'es-AR': 'dd/MM/yyyy',
    'es-BO': 'dd/MM/yyyy',
    'es-CL': 'dd-MM-yyyy',
    'es-CO': 'dd/MM/yyyy',
    'es-CR': 'dd/MM/yyyy',
    'es-DO': 'dd/MM/yyyy',
    'es-EC': 'dd/MM/yyyy',
    'es-ES': 'dd/MM/yyyy',
    'es-GT': 'dd/MM/yyyy',
    'es-HN': 'dd/MM/yyyy',
    'es-MX': 'dd/MM/yyyy',
    'es-NI': 'dd/MM/yyyy',
    'es-PA': 'MM/dd/yyyy',
    'es-PE': 'dd/MM/yyyy',
    'es-PR': 'dd/MM/yyyy',
    'es-PY': 'dd/MM/yyyy',
    'es-SV': 'dd/MM/yyyy',
    'es-US': 'M/d/yyyy',
    'es-UY': 'dd/MM/yyyy',
    'es-VE': 'dd/MM/yyyy',
    'et-EE': 'd.MM.yyyy',
    'eu-ES': 'yyyy/MM/dd',
    'fa-IR': 'MM/dd/yyyy',
    'fi-FI': 'd.M.yyyy',
    'fil-PH': 'M/d/yyyy',
    'fo-FO': 'dd-MM-yyyy',
    'fr-BE': 'd/MM/yyyy',
    'fr-CA': 'yyyy-MM-dd',
    'fr-CH': 'dd.MM.yyyy',
    'fr-FR': 'dd/MM/yyyy',
    'fr-LU': 'dd/MM/yyyy',
    'fr-MC': 'dd/MM/yyyy',
    'fy-NL': 'd-M-yyyy',
    'ga-IE': 'dd/MM/yyyy',
    'gd-GB': 'dd/MM/yyyy',
    'gl-ES': 'dd/MM/yy',
    'gsw-FR': 'dd/MM/yyyy',
    'gu-IN': 'dd-MM-yy',
    'ha-Latn-NG': 'd/M/yyyy',
    'he-IL': 'dd/MM/yyyy',
    'hi-IN': 'dd-MM-yyyy',
    'hr-BA': 'd.M.yyyy.',
    'hr-HR': 'd.M.yyyy',
    'hsb-DE': 'd. M. yyyy',
    'hu-HU': 'yyyy. MM. dd.',
    'hy-AM': 'dd.MM.yyyy',
    'id-ID': 'dd/MM/yyyy',
    'ig-NG': 'd/M/yyyy',
    'ii-CN': 'yyyy/M/d',
    'is-IS': 'd.M.yyyy',
    'it-CH': 'dd.MM.yyyy',
    'it-IT': 'dd/MM/yyyy',
    'iu-Cans-CA': 'd/M/yyyy',
    'iu-Latn-CA': 'd/MM/yyyy',
    'ja-JP': 'yyyy/MM/dd',
    'ka-GE': 'dd.MM.yyyy',
    'kk-KZ': 'dd.MM.yyyy',
    'kl-GL': 'dd-MM-yyyy',
    'km-KH': 'yyyy-MM-dd',
    'kn-IN': 'dd-MM-yy',
    'ko-KR': 'yyyy. MM. dd',
    'kok-IN': 'dd-MM-yyyy',
    'ky-KG': 'dd.MM.yy',
    'lb-LU': 'dd/MM/yyyy',
    'lo-LA': 'dd/MM/yyyy',
    'lt-LT': 'yyyy.MM.dd',
    'lv-LV': 'yyyy.MM.dd.',
    'mi-NZ': 'dd/MM/yyyy',
    'mk-MK': 'dd.MM.yyyy',
    'ml-IN': 'dd-MM-yy',
    'mn-MN': 'yy.MM.dd',
    'mn-Mong-CN': 'yyyy/M/d',
    'moh-CA': 'M/d/yyyy',
    'mr-IN': 'dd-MM-yyyy',
    'ms-BN': 'dd/MM/yyyy',
    'ms-MY': 'dd/MM/yyyy',
    'mt-MT': 'dd/MM/yyyy',
    'nb-NO': 'dd.MM.yyyy',
    'ne-NP': 'M/d/yyyy',
    'nl-BE': 'd/MM/yyyy',
    'nl-NL': 'd-M-yyyy',
    'nn-NO': 'dd.MM.yyyy',
    'nso-ZA': 'yyyy/MM/dd',
    'oc-FR': 'dd/MM/yyyy',
    'or-IN': 'dd-MM-yy',
    'pa-IN': 'dd-MM-yy',
    'pl-PL': 'dd.MM.yyyy',
    'prs-AF': 'dd/MM/yy',
    'ps-AF': 'dd/MM/yy',
    'pt-BR': 'd/M/yyyy',
    'pt-PT': 'dd-MM-yyyy',
    'qut-GT': 'dd/MM/yyyy',
    'quz-BO': 'dd/MM/yyyy',
    'quz-EC': 'dd/MM/yyyy',
    'quz-PE': 'dd/MM/yyyy',
    'rm-CH': 'dd/MM/yyyy',
    'ro-RO': 'dd.MM.yyyy',
    'ru-RU': 'dd.MM.yyyy',
    'rw-RW': 'M/d/yyyy',
    'sa-IN': 'dd-MM-yyyy',
    'sah-RU': 'MM.dd.yyyy',
    'se-FI': 'd.M.yyyy',
    'se-NO': 'dd.MM.yyyy',
    'se-SE': 'yyyy-MM-dd',
    'si-LK': 'yyyy-MM-dd',
    'sk-SK': 'd. M. yyyy',
    'sl-SI': 'd.M.yyyy',
    'sma-NO': 'dd.MM.yyyy',
    'sma-SE': 'yyyy-MM-dd',
    'smj-NO': 'dd.MM.yyyy',
    'smj-SE': 'yyyy-MM-dd',
    'smn-FI': 'd.M.yyyy',
    'sms-FI': 'd.M.yyyy',
    'sq-AL': 'yyyy-MM-dd',
    'sr-Cyrl-BA': 'd.M.yyyy',
    'sr-Cyrl-CS': 'd.M.yyyy',
    'sr-Cyrl-ME': 'd.M.yyyy',
    'sr-Cyrl-RS': 'd.M.yyyy',
    'sr-Latn-BA': 'd.M.yyyy',
    'sr-Latn-CS': 'd.M.yyyy',
    'sr-Latn-ME': 'd.M.yyyy',
    'sr-Latn-RS': 'd.M.yyyy',
    'sv-FI': 'd.M.yyyy',
    'sv-SE': 'yyyy-MM-dd',
    'sw-KE': 'M/d/yyyy',
    'syr-SY': 'dd/MM/yyyy',
    'ta-IN': 'dd-MM-yyyy',
    'te-IN': 'dd-MM-yy',
    'tg-Cyrl-TJ': 'dd.MM.yy',
    'th-TH': 'd/M/yyyy',
    'tk-TM': 'dd.MM.yy',
    'tn-ZA': 'yyyy/MM/dd',
    'tr-TR': 'dd.MM.yyyy',
    'tt-RU': 'dd.MM.yyyy',
    'tzm-Latn-DZ': 'dd-MM-yyyy',
    'ug-CN': 'yyyy-M-d',
    'uk-UA': 'dd.MM.yyyy',
    'ur-PK': 'dd/MM/yyyy',
    'uz-Cyrl-UZ': 'dd.MM.yyyy',
    'uz-Latn-UZ': 'dd/MM yyyy',
    'vi-VN': 'dd/MM/yyyy',
    'wo-SN': 'dd/MM/yyyy',
    'xh-ZA': 'yyyy/MM/dd',
    'yo-NG': 'd/M/yyyy',
    'zh-CN': 'yyyy/M/d',
    'zh-HK': 'd/M/yyyy',
    'zh-MO': 'd/M/yyyy',
    'zh-SG': 'd/M/yyyy',
    'zh-TW': 'yyyy/M/d',
    'zu-ZA': 'yyyy/MM/dd',
  },
};
